service: coinbase-trader

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 900
  memorySize: 2048
  environment:
    # Use direct environment variables instead of Secrets Manager
    SECRET_KEY: ${env:SECRET_KEY, ''}
    DB_PATH: ${env:DB_PATH, '/tmp/db'}
  # Standard IAM role permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  getBacktestHistory:
    handler: lambda_functions/backtest_history_lambda.lambda_handler
    events:
      - httpApi:
          path: /api/backtests
          method: get
  
  getCandles:
    handler: lambda_functions/get_candles_lambda.lambda_handler
    timeout: 900
    events:
      - httpApi:
          path: /api/candles
          method: get
      - schedule: rate(1 hour)
  
  runHyperOptimization:
    handler: lambda_functions/run_hyper_lambda.lambda_handler
    timeout: 900
    memorySize: 3008
    events:
      - httpApi:
          path: /api/hyperopt
          method: post

package:
  exclude:
    - node_modules/**
    - .git/**
    - .env
    - __pycache__/**
    - '**/*.pyc'
  include:
    - lambda_functions/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true